### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by jalexhurt** [FireLemons/AIHW2#1]
Form1.cs can't find AStar.cs?
Help requested!

**Comment by FireLemons** [comment]
I clicked on the project and right clicked AStar.cs and selected include in project to get it to run but that caused more errors.

**Comment by FireLemons** [comment]
You can also try removing the line `<Compile Include="AStar.cs" />` from `CS4750HW2.csproj`

**Comment by FireLemons** [comment]
Does checking out the last successful commit work?

**Comment by jalexhurt** [comment]
No. See next comment for output

**Comment by jalexhurt** [comment]
<pre>
1>------ Build started: Project: CS4750HW2, Configuration: Debug|AnyCPU ------
C:\Users\hurtja\Source\Repos\AIHW2\CS4750HW2\AStar.cs(107,162,107,170): error CS1503: Argument 4: cannot convert from 'CS4750HW2.Direction' to 'int[*,*]'
C:\Users\hurtja\Source\Repos\AIHW2\CS4750HW2\Form1.cs(189,25,189,43): error CS0120: An object reference is required for the non-static field, method, or property 'AStar.doTreeSearch()'
C:\Users\hurtja\Source\Repos\AIHW2\CS4750HW2\DFS.cs(34,17,34,30): warning CS0219: The variable 'nodesExpanded' is assigned but its value is never used
C:\Users\hurtja\Source\Repos\AIHW2\CS4750HW2\DFS.cs(14,34,14,40): warning CS0169: The field 'DFS.fringe' is never used
C:\Users\hurtja\Source\Repos\AIHW2\CS4750HW2\DFS.cs(13,30,13,36): warning CS0169: The field 'DFS.closed' is never used
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
</pre>

**Comment by jalexhurt** [comment]
Got it working!
This is the commit that fixed the issue: https://github.com/FireLemons/AIHW2/tree/18a5514a2c9ac4af0c2df71fd114a7a9584aa3b2
